[package]
name = "bevy-tablestakes"
description = "hey!!! I'm walkin here!!!"
authors = ["Nick Fagerlund", "Motorsprite Chaos Industries"]
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = { version = "0.6.1", features = [
    "dynamic",
] }
bevy_ecs_tilemap = "0.5.0"
# bevy_ecs_ldtk = "0.2.0"
# It looks like LDTK upgrades itself without asking, and tbh I'd rather use
# latest/greatest for the most part anyway, so I need to use the ldtk-1.0 branch
# of this crate:
bevy_ecs_ldtk = { git = "https://github.com/Trouv/bevy_ecs_ldtk.git", rev = "a6e4003fbe33945f5e0dc3384a697497caae866a" }
# bevy_mod_debugdump = "0.3.0" # neat: https://github.com/jakobhellermann/bevy_mod_debugdump

# Per https://bevy-cheatbook.github.io/pitfalls/performance.html:
# medium-optimize this crate's own debug builds
[profile.dev]
opt-level = 1

# hella optimize all the engine dependencies
[profile.dev.package."*"]
opt-level = 3
